src/AppBundle/Entity/Answer.php
<?php

namespace AppBundle\Entity;

use ModernFactory\ResourcesBundle\Resource\Model\ResourceInterface;

class Answer implements ResourceInterface
{
    /** @var integer */
    protected $id;
    /** @var \DateTime */
    protected $createdAt;
    /** @var \DateTime */
    protected $updatedAt;
    /** @var string */
    protected $content;
    /** @var Challenge */
    protected $challenge;
    /** @var string */
    protected $deviceBrand;
    /** @var string */
    protected $deviceModel;
    /** @var string */
    protected $deviceOS;
    /** @var string */
    protected $deviceOSVersion;
    /** @var string */
    protected $timeResult;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return string
     */
    public function getDeviceBrand()
    {
        return $this->deviceBrand;
    }

    /**
     * @param string $deviceBrand
     */
    public function setDeviceBrand($deviceBrand)
    {
        $this->deviceBrand = $deviceBrand;
    }

    /**
     * @return string
     */
    public function getDeviceModel()
    {
        return $this->deviceModel;
    }

    /**
     * @param string $deviceModel
     */
    public function setDeviceModel($deviceModel)
    {
        $this->deviceModel = $deviceModel;
    }

    /**
     * @return string
     */
    public function getDeviceOS()
    {
        return $this->deviceOS;
    }

    /**
     * @param string $deviceOS
     */
    public function setDeviceOS($deviceOS)
    {
        $this->deviceOS = $deviceOS;
    }

    /**
     * @return string
     */
    public function getDeviceOSVersion()
    {
        return $this->deviceOSVersion;
    }

    /**
     * @param string $deviceOSVersion
     */
    public function setDeviceOSVersion($deviceOSVersion)
    {
        $this->deviceOSVersion = $deviceOSVersion;
    }

    /**
     * @return string
     */
    public function getTimeResult()
    {
        return $this->timeResult;
    }

    /**
     * @param string $timeResult
     */
    public function setTimeResult($timeResult)
    {
        $this->timeResult = $timeResult;
    }

    public function isCorrect()
    {
        return strtolower($this->getContent()) === strtolower($this->getChallenge()->getCorrectAnswer());
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * @return Challenge
     */
    public function getChallenge()
    {
        return $this->challenge;
    }

    /**
     * @param Challenge $challenge
     */
    public function setChallenge(Challenge $challenge)
    {
        $this->challenge = $challenge;
    }
}

src/AppBundle/Entity/Image.php
<?php

namespace AppBundle\Entity;

use ModernFactory\ResourcesBundle\Resource\Model\ResourceInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class Image implements ResourceInterface
{
    /** @var string */
    protected $id;
    /** @var string */
    protected $filesystem;
    /** @var string */
    protected $originalName;
    /** @var string */
    protected $imageName;
    /** @var string */
    protected $mimeType;
    /** @var int */
    protected $size;
    /** @var Challenge */
    protected $challenge;
    /** @var \DateTime */
    protected $updatedAt;
    /** @var \DateTime */
    protected $createdAt;
    /** @var string */
    protected $url;
    /** @var UploadedFile */
    protected $imageFile;

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getFilesystem()
    {
        return $this->filesystem;
    }

    /**
     * @param string $filesystem
     */
    public function setFilesystem($filesystem)
    {
        $this->filesystem = $filesystem;
    }

    /**
     * @return string
     */
    public function getOriginalName()
    {
        return $this->originalName;
    }

    /**
     * @param string $originalName
     */
    public function setOriginalName($originalName)
    {
        $this->originalName = $originalName;
    }

    /**
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * @param string $imageName
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;
    }

    /**
     * @return mixed
     */
    public function getSize()
    {
        return $this->size;
    }

    /**
     * @param mixed $size
     */
    public function setSize($size)
    {
        $this->size = $size;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * @param string $url
     */
    public function setUrl($url)
    {
        $this->url = $url;
    }

    /**
     * Get image file.
     *
     * @return UploadedFile
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $imageFile
     */
    public function setImageFile(UploadedFile $imageFile = null)
    {
        $this->imageFile = $imageFile;
        if ($imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    /**
     * @return string
     */
    public function getMimeType()
    {
        return $this->mimeType;
    }

    /**
     * @param string $mimeType
     */
    public function setMimeType($mimeType)
    {
        $this->mimeType = $mimeType;
    }

    public function getImagePath()
    {
        return null === $this->imageName
            ? null
            : $this->getUploadDir() . '/' . $this->imageName;
    }

    public function getUploadDir()
    {
        return 'images';
    }

    public function getAbsoluteImagePath()
    {
        return null === $this->imageName
            ? null
            : $this->getUploadDir() . '/' . $this->imageName;
    }

    /**
     * @return Challenge
     */
    public function getChallenge()
    {
        return $this->challenge;
    }

    /**
     * @param Challenge $challenge
     */
    public function setChallenge(Challenge $challenge)
    {
        $this->challenge = $challenge;
    }
}

src/AppBundle/Form/AnswerType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Answer;
use AppBundle\Entity\Challenge;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Validator\Constraints\Type;

class AnswerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content', TextType::class, [
                'description' => 'Text content',
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('challenge', EntityType::class, [
                'description' => 'Challenge',
                'label' => 'challenge',
                'class' => Challenge::class,
                'choice_label' => 'name',
                'expanded' => false,
                'multiple' => false,
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('deviceBrand', TextType::class, [
                'description' => 'Device brand',
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('deviceModel', TextType::class, [
                'description' => 'Device model',
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('deviceOS', TextType::class, [
                'description' => 'Device operating system',
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('deviceOSVersion', TextType::class, [
                'description' => 'Device operating system version',
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('timeResult', TextType::class, [
                'description' => 'Time result',
                'constraints' => [
                    new NotBlank(),
                    new Range([
                        'min' => 0
                    ])
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'csrf_protection' => false,
            'data_class' => Answer::class,
        ]);
    }

    public function getBlockPrefix()
    {
        return '';
    }
}

src/AppBundle/Controller/Api/AnswerController.php
<?php

namespace AppBundle\Controller\Api;

use AppBundle\Entity\Answer;
use AppBundle\Form\AnswerType;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMInvalidArgumentException;
use FOS\RestBundle\Controller\Annotations as Rest;
use InvalidArgumentException;
use Nelmio\ApiDocBundle\Annotation\ApiDoc;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\OptionsResolver\Exception\InvalidOptionsException;

class AnswerController extends ApiController
{
    /**
     * @ApiDoc(
     *   section = "answer",
     *   description = "Post answer",
     *   views = {"default"},
     *   authentication = true,
     *   authenticationRoles = {"ROLE_USER"},
     *   resource = true,
     *   statusCodes = {
     *     204 = "Success",
     *     400 = "Invalid params",
     *     418 = "Invalid answer",
     *     401 = "Authentication required",
     *     403 = "Unauthorized",
     *     404 = "Not found"
     *   },
     *   input= {
     *      "class" = "AppBundle\Form\AnswerType"
     *   }
     * )
     *
     * @Rest\Post("/answers")
     *
     * @param Request $request
     *
     * @return Response
     *
     * @throws OptimisticLockException
     * @throws ORMInvalidArgumentException
     * @throws HttpException
     * @throws InvalidArgumentException
     * @throws InvalidOptionsException
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     */
    public function postAction(Request $request): Response
    {
        $answer = new Answer();
        $form = $this->get('form.factory')->createNamed('', AnswerType::class, $answer);

        $this->handleForm($form, $request);
        if (!$form->isValid()) {
            return $this->createValidationErrorResponse($form);
        }

        if (!$answer->isCorrect()) {
            throw new HttpException(418, 'Your answer is incorrect.');
        }

        $this->get('app.answer_repository')->save($answer);

        return $this->response([], 204);
    }
}

src/AppBundle/Controller/Front/Admin/AnswerController.php
<?php

namespace AppBundle\Controller\Front\Admin;

use AppBundle\Entity\Answer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class AnswerController extends Controller
{
    /**
     * @Route("/answers", name="admin_answer_index")
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws \Pagerfanta\Exception\OutOfRangeCurrentPageException
     * @throws \Pagerfanta\Exception\NotIntegerCurrentPageException
     * @throws \Pagerfanta\Exception\LessThan1CurrentPageException
     */
    public function indexAction(Request $request)
    {
        return $this->render(
            'AppBundle:Admin/Answer:index.html.twig', [
                'paginator' => $this->get('app.answer_repository')->createAnswerPaginator(
                    [
                        'query' => $request->get('q', null)
                    ],
                    $request->get('sorting', [])
                )->setCurrentPage($request->get('page', 1))
            ]
        );
    }

    /**
     * @Route("/answers/{id}/delete", name="admin_answer_delete")
     *
     * @param Answer $answer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws \Doctrine\ORM\ORMInvalidArgumentException
     * @throws \LogicException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function deleteAction(Answer $answer)
    {
        $this->get('app.challenge_repository')->remove($answer);
        $this->addFlash('success', $this->get('translator')->trans('answer.delete.success'));

        return $this->redirectToRoute('admin_answer_index');
    }
}

src/AppBundle/Resources/views/Admin/Answer/index.html.twig
{% from 'AppBundle::pagination.html.twig' import pagination %}

{% extends "AppBundle::layout.html.twig" %}
{% block title %}{{ 'answer.list.header'|trans }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title pull-left">{{ 'answer.list.header'|trans }}</h3>
                    <a href="{{ path('admin_answer_index') }}" class="btn btn-sm btn-primary pull-right">
                        <i class="fa fa-plus"></i> {{ 'answer.list.add_button'|trans }}
                    </a>
                    <div class="col-md-3 pull-right">
                        <form method="get">
                            <div class="form-group input-group">
                                <input name="q" type="text" class="form-control" value="{{ app.request.get('q') }}">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover table-striped">
                            <thead>
                            <tr>
                                <th>{{ resources_bundle_sort('deviceBrand', 'answer.deviceBrand'|trans) }}</th>
                                <th>{{ resources_bundle_sort('deviceModel', 'answer.deviceModel'|trans) }}</th>
                                <th>{{ resources_bundle_sort('deviceOS', 'answer.deviceOS'|trans) }}</th>
                                <th>{{ resources_bundle_sort('deviceOSVersion', 'answer.deviceOSVersion'|trans) }}</th>
                                <th>{{ resources_bundle_sort('timeResult', 'answer.timeResult'|trans) }}</th>
                                <th class="text-right">{{ 'image'|trans }}</th>
                                <th>{{ resources_bundle_sort('createdAt', 'challenge.createdAt'|trans) }}</th>
                                <th class="text-right">{{ 'actions'|trans }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if paginator|length == 0 %}
                                <tr>
                                    <td class="text-center" colspan="6">
                                        {% if app.request.get('q') %}
                                            {{ 'answer.list.search.not.found'|trans }}
                                        {% else %}
                                            {{ 'answer.list.not.found'|trans }}
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endif %}
                            {# answer \AppBundle\Entity\\AppBundle\Entity\Answer #}
                            {% for answer in paginator %}
                                <tr>
                                    <td>{{ answer.deviceBrand }}</td>
                                    <td>{{ answer.deviceModel }}</td>
                                    <td>{{ answer.deviceOS }}</td>
                                    <td>{{ answer.deviceOSVersion }}</td>
                                    <td>{{ answer.timeResult }}</td>
                                    <td>
                                        <img src="{{ answer.challenge.image.imagePath|imagine_filter('list') }}"/>
                                    </td>
                                    <td>
                                        {{ answer.createdAt|date }}
                                    </td>
                                    <td class="text-right">
                                        <a href="{{ path('admin_answer_delete', {'id': answer.id}) }}"
                                           class="btn btn-xs btn-danger">
                                            <i class="fa fa-times"></i> {{ 'remove'|trans }}
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {{ pagination(paginator) }}
        </div>
    </div>
{% endblock %}